#!/usr/bin/python3
#
# This file is part of Cloudbox.
#
# Copyright 2011 Canonical Ltd.
#
# Cloudbox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Cloudbox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cloudbox.  If not, see <http://www.gnu.org/licenses/>.
#
import os
import sys

from cloudbox.parsers.efi import EfiParser


# Command to retrieve efi information.
COMMAND = "[ -d /sys/firmware/efi ] && grep -o --color=never 'EFI v.*' /var/log/kern.log || true"


class EfiResult:

    attributes = ("path", "category", "product", "vendor",)

    def setEfiDevice(self, device):
        for attribute in self.attributes:
            value = getattr(device, attribute, None)
            if value is not None:
                print("%s: %s" % (attribute, value))

        print()


def main():
    stream = os.popen(COMMAND)
    efi = EfiParser(stream)

    result = EfiResult()
    efi.run(result)

    return 0


if __name__ == "__main__":
    sys.exit(main())
