#!/usr/bin/python3
#
# This file is part of Cloudbox.
#
# Copyright 2009 Canonical Ltd.
#
# Cloudbox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Cloudbox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cloudbox.  If not, see <http://www.gnu.org/licenses/>.
#
import sys

from cloudbox.parsers.meminfo import MeminfoParser

# Filename where meminfo is stored.
MEMINFO_FILENAME = "/proc/meminfo"


class MeminfoResult:

    def setMemory(self, memory):
        for key, value in memory.items():
            print("%s: %s" % (key, value))


def main():
    stream = open(MEMINFO_FILENAME)
    parser = MeminfoParser(stream)

    result = MeminfoResult()
    parser.run(result)

    return 0


if __name__ == "__main__":
    sys.exit(main())
