#!/usr/bin/python3
#
# This file is part of Cloudbox.
#
# Copyright 2009 Canonical Ltd.
#
# Cloudbox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Cloudbox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cloudbox.  If not, see <http://www.gnu.org/licenses/>.
#
import os
import sys


def get_uname():
    keys = ("name", "node", "release", "version", "machine")
    values = os.uname()
    return dict(list(zip(keys, values)))


def main():
    uname = get_uname()
    for key, value in uname.items():
        print("%s: %s" % (key, value))

    return 0


if __name__ == "__main__":
    sys.exit(main())
