#!/usr/bin/python3
import os
import sys

from plainbox.impl.runner import JobRunner


def main():
    if os.getuid() != 0:
        print("Was expecting to run as superuser")
        return -2
    runner = JobRunner(checkbox, session_dir, jobs_io_log_dir)


if __name__ == "__main__":
    raise SystemExit(main())
